# -*- mode: ruby -*-
# vi: set ft=ruby :

machines = [
  {
    :name     => "rainfall",
    :image    => "rainfall",
    :iso      => "rainfall.iso",
    :hostname => "rainfall",
    :memory   => "12288",
    :cpus     => "8",
  }
]

Vagrant.configure("2") do |config|
  machines.each do |machine|
    config.vm.define machine[:name] do |node|

      node.vm.box = machine[:image]
      node.vm.box_url = "file://#{File.dirname(__FILE__)}/#{machine[:iso]}"
      node.vm.hostname = machine[:hostname]

      node.vm.provider "virtualbox" do |vb|
        vb.name   = machine[:name]
        vb.memory = machine[:memory]
        vb.cpus   = machine[:cpus]
      end

      node.vm.synced_folder ".", "/vagrant", disabled: true

      node.vm.provision "shell", inline: <<~SHELL
        apt-get update
        useradd -m -s /bin/bash lnicolof
        echo "lnicolof:lnicolof" | chpasswd
        usermod -aG sudo lnicolof
      SHELL

    end
  end
end